import { MigrationInterface, QueryRunner } from "typeorm";

export class FixEntityRelations1755630204356 implements MigrationInterface {
    name = 'FixEntityRelations1755630204356'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "businesses_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "student_talents" DROP CONSTRAINT "student_talents_student_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "skills_student_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "projects_student_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "achievements" DROP CONSTRAINT "achievements_student_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "students_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "messages_conversation_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "applications_job_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "applications_student_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "deliverables" DROP CONSTRAINT "deliverables_job_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "jobs_business_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP CONSTRAINT "milestones_job_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "conversation_participants_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "conversation_participants_conversation_id_fkey"`);
        await queryRunner.query(`CREATE TYPE "public"."collaborations_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "collaborations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requesterId" uuid NOT NULL, "recipientId" uuid NOT NULL, "talentId" uuid, "message" text NOT NULL, "status" "public"."collaborations_status_enum" NOT NULL DEFAULT 'pending', "responseMessage" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6d843532637cb55b078793e6811" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "students_skills_skills" ("studentsId" uuid NOT NULL, "skillsId" uuid NOT NULL, CONSTRAINT "PK_6ac3529bea76e3d739e45ce31f7" PRIMARY KEY ("studentsId", "skillsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_52ecd9144b73a0aebca98636f8" ON "students_skills_skills" ("studentsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_142c5fef6137ea9b13777df4f9" ON "students_skills_skills" ("skillsId") `);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "students_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "profile_views"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "year"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "about"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "profile_image"`);
        await queryRunner.query(`ALTER TABLE "students" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "students" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "students" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "UQ_25985d58c714a4a427ced57507b" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "students" ADD "bio" character varying`);
        await queryRunner.query(`ALTER TABLE "students" ADD "graduationYear" character varying`);
        await queryRunner.query(`ALTER TABLE "students" ADD "gpa" character varying`);
        await queryRunner.query(`ALTER TABLE "students" ADD "profileImage" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."students_role_enum" AS ENUM('student', 'business', 'admin')`);
        await queryRunner.query(`ALTER TABLE "students" ADD "role" "public"."students_role_enum" NOT NULL DEFAULT 'student'`);
        await queryRunner.query(`ALTER TABLE "students" ADD "likedTalents" text`);
        await queryRunner.query(`ALTER TABLE "students" ADD "savedTalents" text`);
        await queryRunner.query(`ALTER TABLE "students" ADD "collaborations" text`);
        await queryRunner.query(`ALTER TABLE "students" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "students" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "business_name"`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "business_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "businesses_email_key"`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "UQ_ee58c14c74529ea227d8337ab69" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "business_type"`);
        await queryRunner.query(`CREATE TYPE "public"."businesses_business_type_enum" AS ENUM('TECHNOLOGY', 'CONSULTING', 'HEALTHCARE', 'FINANCE', 'EDUCATION', 'RETAIL')`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "business_type" "public"."businesses_business_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "location" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "website" character varying`);
        await queryRunner.query(`ALTER TABLE "student_talents" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "student_talents" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "proficiency"`);
        await queryRunner.query(`CREATE TYPE "public"."skills_proficiency_enum" AS ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "proficiency" "public"."skills_proficiency_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievements" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "achievements" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievements" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "achievements" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "major"`);
        await queryRunner.query(`ALTER TABLE "students" ADD "major" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('student', 'business', 'admin')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "agreed_to_terms" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "sender_id"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "sender_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "receiver_id"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "receiver_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "content"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "content" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."applications_status_enum" AS ENUM('PENDING', 'REVIEWED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN')`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "status" "public"."applications_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliverables" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "deliverables" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliverables" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "deliverables" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliverables" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "deliverables" ADD "status" character varying NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "deliverables" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_type_enum" AS ENUM('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT', 'FREELANCE')`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "type" "public"."jobs_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "experience_level"`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_experience_level_enum" AS ENUM('ENTRY_LEVEL', 'INTERMEDIATE', 'SENIOR')`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "experience_level" "public"."jobs_experience_level_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "location" character varying`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "salary"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "salary" character varying`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."milestones_status_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED')`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD "status" "public"."milestones_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "milestones" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_1559e8a16b828f2e836a231280" ON "conversation_participants" ("conversation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_377d4041a495b81ee1a85ae026" ON "conversation_participants" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "FK_cbb98c2d1e4c7bdf6eabc305c42" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_talents" ADD CONSTRAINT "FK_c6efbbc3a27d37fe8070f0283b1" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_739f2dd8faf279ff6ba6dd4180b" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievements" ADD CONSTRAINT "FK_f4f0c6065670e5a3d6f53b18acb" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collaborations" ADD CONSTRAINT "FK_3690b4c77912530170ef7b9f450" FOREIGN KEY ("requesterId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collaborations" ADD CONSTRAINT "FK_7dda1f4b56b9310e979acdacc84" FOREIGN KEY ("recipientId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collaborations" ADD CONSTRAINT "FK_22c2eeae4e2f71f6d4f25277366" FOREIGN KEY ("talentId") REFERENCES "student_talents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_791e5e9cf054d0295ebfe4491a9" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_8aba14d7f098c23ba06d8693235" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deliverables" ADD CONSTRAINT "FK_71d52262573809ee3d68964afe4" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_6866bb3c271a60ec9156aa84569" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD CONSTRAINT "FK_b60d370f83418e598211094bae8" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students_skills_skills" ADD CONSTRAINT "FK_52ecd9144b73a0aebca98636f81" FOREIGN KEY ("studentsId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "students_skills_skills" ADD CONSTRAINT "FK_142c5fef6137ea9b13777df4f99" FOREIGN KEY ("skillsId") REFERENCES "skills"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_1559e8a16b828f2e836a2312800" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_377d4041a495b81ee1a85ae026f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_377d4041a495b81ee1a85ae026f"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_1559e8a16b828f2e836a2312800"`);
        await queryRunner.query(`ALTER TABLE "students_skills_skills" DROP CONSTRAINT "FK_142c5fef6137ea9b13777df4f99"`);
        await queryRunner.query(`ALTER TABLE "students_skills_skills" DROP CONSTRAINT "FK_52ecd9144b73a0aebca98636f81"`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP CONSTRAINT "FK_b60d370f83418e598211094bae8"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_6866bb3c271a60ec9156aa84569"`);
        await queryRunner.query(`ALTER TABLE "deliverables" DROP CONSTRAINT "FK_71d52262573809ee3d68964afe4"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_8aba14d7f098c23ba06d8693235"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_791e5e9cf054d0295ebfe4491a9"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "collaborations" DROP CONSTRAINT "FK_22c2eeae4e2f71f6d4f25277366"`);
        await queryRunner.query(`ALTER TABLE "collaborations" DROP CONSTRAINT "FK_7dda1f4b56b9310e979acdacc84"`);
        await queryRunner.query(`ALTER TABLE "collaborations" DROP CONSTRAINT "FK_3690b4c77912530170ef7b9f450"`);
        await queryRunner.query(`ALTER TABLE "achievements" DROP CONSTRAINT "FK_f4f0c6065670e5a3d6f53b18acb"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_739f2dd8faf279ff6ba6dd4180b"`);
        await queryRunner.query(`ALTER TABLE "student_talents" DROP CONSTRAINT "FK_c6efbbc3a27d37fe8070f0283b1"`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "FK_cbb98c2d1e4c7bdf6eabc305c42"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_377d4041a495b81ee1a85ae026"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1559e8a16b828f2e836a231280"`);
        await queryRunner.query(`ALTER TABLE "milestones" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."milestones_status_enum"`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD "status" character varying(20) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "salary"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "salary" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "location" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "experience_level"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_experience_level_enum"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "experience_level" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_type_enum"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "type" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "description" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliverables" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliverables" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "deliverables" ADD "status" character varying(20) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "deliverables" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "deliverables" ADD "description" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliverables" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "deliverables" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "applications" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."applications_status_enum"`);
        await queryRunner.query(`ALTER TABLE "applications" ADD "status" character varying(20) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "content"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "content" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "receiver_id"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "receiver_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "sender_id"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "sender_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "agreed_to_terms" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" character varying(20) NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "major"`);
        await queryRunner.query(`ALTER TABLE "students" ADD "major" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievements" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "achievements" ADD "description" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "achievements" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "achievements" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "description" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "proficiency"`);
        await queryRunner.query(`DROP TYPE "public"."skills_proficiency_enum"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "proficiency" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "student_talents" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "student_talents" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "website" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "location" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "business_type"`);
        await queryRunner.query(`DROP TYPE "public"."businesses_business_type_enum"`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "business_type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "UQ_ee58c14c74529ea227d8337ab69"`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "businesses_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP COLUMN "business_name"`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD "business_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "collaborations"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "savedTalents"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "likedTalents"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."students_role_enum"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "profileImage"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "gpa"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "graduationYear"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "bio"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "UQ_25985d58c714a4a427ced57507b"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "students" ADD "profile_image" character varying`);
        await queryRunner.query(`ALTER TABLE "students" ADD "about" text`);
        await queryRunner.query(`ALTER TABLE "students" ADD "year" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "students" ADD "last_name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "students" ADD "first_name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "students" ADD "profile_views" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "students" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "students_user_id_key" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "image" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "student_id" uuid`);
        await queryRunner.query(`DROP INDEX "public"."IDX_142c5fef6137ea9b13777df4f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52ecd9144b73a0aebca98636f8"`);
        await queryRunner.query(`DROP TABLE "students_skills_skills"`);
        await queryRunner.query(`DROP TABLE "collaborations"`);
        await queryRunner.query(`DROP TYPE "public"."collaborations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD CONSTRAINT "milestones_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "jobs_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deliverables" ADD CONSTRAINT "deliverables_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "applications_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "applications_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "students_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievements" ADD CONSTRAINT "achievements_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "projects_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "skills_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_talents" ADD CONSTRAINT "student_talents_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "businesses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
